x-environment: &x-environment
  PROXY_SERVER: http://bobcatdev.library.nyu.edu:80
  VIEW: ${VIEW-NYU}
  NODE_ENV: ${NODE_ENV-development}
  VE:
  SAML:
  CAS:
  PACK:

x-defaults: &x-defaults
  build:
    context: .
    cache_from:
      - primo-explore-views
      - quay.io/nyulibraries/primo-explore-views
      - quay.io/nyulibraries/primo-explore-views:$BRANCH_NO_SLASH
  image: primo-explore-views
  environment:
    <<: *x-environment

version: '3.7'
services:
  web:
    <<: *x-defaults
    ports:
    - 8004:8004
    - 3001:3001
    # volumes:
    # - ./custom:/app/primo-explore/custom/

  web-test:
    <<: *x-defaults
    environment:
      <<: *x-environment
      NODE_ENV: test
    ports:
    - 8004:8004
    - 3001:3001

  create-package:
    <<: *x-defaults
    environment:
      <<: *x-environment
      NODE_ENV: ${NODE_ENV-staging}
      PACK: 'true'
    command: yarn build
    # volumes:
    # - ./packages/:/app/packages

  e2e:
    image: primo-explore-cypress
    build:
      context: .
      dockerfile: cypress/Dockerfile
    # command: cypress run --browser chrome
    depends_on:
      - web-test
    environment:
      <<: *x-environment
      NODE_ENV: test
      CYPRESS_BASE_URL: http://web-test:8004/primo-explore/search
    # volumes:
    # - ./cypress/:/app/cypress
    # - ./custom:/app/primo-explore/custom/