// https://glebbahmutov.com/blog/run-all-specs-cypress-v10/
// ...to work around https://github.com/cypress-io/cypress/discussions/21628

import './BHS/basic-search.cy.js';
import './BHS/home.cy.js';
import './CENTRAL_PACKAGE/basic-search.cy.js';
import './CENTRAL_PACKAGE/custom-no-search-results.cy.js';
import './CENTRAL_PACKAGE/hidden.cy.js';
import './CU/basic-search.cy.js';
import './CU/custom-no-search-results.cy.js';
import './CU/home.cy.js';
import './NYHS/basic-search.cy.js';
import './NYHS/home.cy.js';
import './NYSID/basic-search.cy.js';
import './NYSID/home.cy.js';
import './NYSID/primo-explore-libraryh3lp-widget.cy.js';
import './NYU/basic-search.cy.js';
import './NYU/custom-no-search-results.cy.js';
import './NYU/home.cy.js';
import './NYU/primo-explore-custom-requests.cy.js';
import './NYU/primo-explore-libraryh3lp-widget.cy.js';
import './NYU/send-to-course-reserves.cy.js';
import './NYUAD/basic-search.cy.js';
import './NYUAD/custom-no-search-results.cy.js';
import './NYUAD/home.cy.js';
import './NYUAD/primo-explore-custom-requests.cy.js';
import './NYUAD/primo-explore-libraryh3lp-widget.cy.js';
import './NYUAD/send-to-course-reserves.cy.js';
import './NYUSH/basic-search.cy.js';
import './NYUSH/custom-no-search-results.cy.js';
import './NYUSH/home.cy.js';
import './NYUSH/primo-explore-custom-requests.cy.js';
import './NYUSH/primo-explore-libraryh3lp-widget.cy.js';
import './NYUSH/send-to-course-reserves.cy.js';
import './all.cy.js';
