docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2021.07
  working_directory: ~/app

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      script/pull_docker.sh

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
      script/push_docker.sh

build_docker: &build_docker
  run:
    name: Build Docker images
    command: |
      docker-compose build e2e web web-test

run-e2e-steps: &run-e2e-steps
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Setup custom environment variables
        command: echo 'export BRANCH_NO_SLASH="${CIRCLE_BRANCH//\//_}"' >> $BASH_ENV
    - <<: *pull_docker
    - run:
        name: Run View E2E Tests
        command: |
          script/run_view_e2e_test.sh
    - store_artifacts:
        path: cypress-results
    - store_test_results:
        path: cypress-results/test-results

version: 2
jobs:
  run-unit-tests:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Runs unit tests in Jest
          command: |
            mkdir -p junit
            docker-compose build unit-test
            docker-compose run unit-test
            docker cp "$(docker ps -q -a -l -f name=unit-test)":/app/custom/spec/coverage/. coverage
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

  run-e2e-BHS:
    <<: *docker-defaults
    environment:
      VIEW: BHS
    <<: *run-e2e-steps
  run-e2e-CENTRAL_PACKAGE:
    <<: *docker-defaults
    environment:
      VIEW: CENTRAL_PACKAGE
    <<: *run-e2e-steps
  run-e2e-CU:
    <<: *docker-defaults
    environment:
      VIEW: CU
    <<: *run-e2e-steps
  run-e2e-NYHS:
    <<: *docker-defaults
    environment:
      VIEW: NYHS
    <<: *run-e2e-steps
  run-e2e-NYSID:
    <<: *docker-defaults
    environment:
      VIEW: NYSID
    <<: *run-e2e-steps
  run-e2e-NYU:
    <<: *docker-defaults
    environment:
      VIEW: NYU
    <<: *run-e2e-steps
  run-e2e-NYUAD:
    <<: *docker-defaults
    environment:
      VIEW: NYUAD
    <<: *run-e2e-steps
  run-e2e-NYUSH:
    <<: *docker-defaults
    environment:
      VIEW: NYUSH
    <<: *run-e2e-steps

  create-view-packages:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup custom environment variables
          command: echo 'export BRANCH_NO_SLASH="${CIRCLE_BRANCH//\//_}"' >> $BASH_ENV
      - <<: *pull_docker
      - run:
          name: Build asset VIEW package and store
          command: script/create_view_packages.sh
      - store_artifacts:
          path: packages

  push-docker-images:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup custom environment variables
          command: echo 'export BRANCH_NO_SLASH="${CIRCLE_BRANCH//\//_}"' >> $BASH_ENV
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *push_docker

workflows:
  version: 2
  build-test-and-deliver:
    jobs:
    - run-unit-tests
    - run-e2e-BHS:
        requires:
        - run-unit-tests
    - run-e2e-CENTRAL_PACKAGE:
        requires:
        - run-unit-tests
    - run-e2e-CU:
        requires:
        - run-unit-tests
    - run-e2e-NYHS:
        requires:
        - run-unit-tests
    - run-e2e-NYSID:
        requires:
        - run-unit-tests
    - run-e2e-NYU:
        requires:
        - run-unit-tests
    - run-e2e-NYUAD:
        requires:
        - run-unit-tests
    - run-e2e-NYUSH:
        requires:
        - run-unit-tests
    - push-docker-images:
        requires:
        - run-e2e-BHS
        - run-e2e-CENTRAL_PACKAGE
        - run-e2e-CU
        - run-e2e-NYHS
        - run-e2e-NYSID
        - run-e2e-NYU
        - run-e2e-NYUAD
        - run-e2e-NYUSH
    - create-view-packages:
        requires:
        - run-e2e-BHS
        - run-e2e-CENTRAL_PACKAGE
        - run-e2e-CU
        - run-e2e-NYHS
        - run-e2e-NYSID
        - run-e2e-NYU
        - run-e2e-NYUAD
        - run-e2e-NYUSH
