docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      docker-compose build web e2e

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      script/pull_docker.sh

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      script/push_docker.sh

test: &test-and-store
  run:
    name: Run E2E Tests
    command: |
      script/run_tests.sh

version: 2
jobs:
  build-and-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check package_jsons.tgz
          command: |
            script/tgz_packages.sh
      - <<: *auth_quay
      # - <<: *pull_docker
      - <<: *build_docker
      - <<: *test-and-store
      - <<: *push_docker
      - store_artifacts:
          path: cypress-results/videos
      - store_artifacts:
          path: cypress-results/screenshots
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
  create-package:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      # - <<: *pull_docker
      - run:
          name: Build asset package and store
          command: script/create_package.sh

      - store_artifacts:
          path: packages

workflows:
  version: 2
  build:
    jobs:
    - build-and-test
    - create-package:
        requires:
          - build-and-test

