docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
  working_directory: ~/app


pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      script/pull_docker.sh

version: 2
jobs:
  build-and-push-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate Quay
          command: |
            docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
      - <<: *pull_docker
      - run:
          name: Build Docker
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build web e2e
      - run:
          name: Push Docker
          command: |
            script/push_docker.sh

  run-views-e2e-tests:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *pull_docker
      - run:
          name: Run E2E Tests
          command: |
            script/run_view_e2e_tests.sh
      - store_artifacts:
          path: cypress-results
      - store_test_results:
          path: cypress-results/test-results

  create-view-packages:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *pull_docker
      - run:
          name: Build asset package and store
          command: script/create_view_packages.sh
      - store_artifacts:
          path: packages

  run-module-unit-tests:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run unit tests
          command: script/run_module_unit_tests.sh
      - store_artifacts:
          path: karma-unit-test-results
      - store_test_results:
          path: karma-unit-test-results

workflows:
  version: 2
  build-test-and-deliver:
    jobs:
    - build-and-push-image
    - run-module-unit-tests:
        requires:
        - build-and-push-image
    - run-views-e2e-tests:
        requires:
        - build-and-push-image
    - create-view-packages:
        requires:
        - run-views-e2e-tests
        - run-module-unit-tests

