docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      docker-compose build web e2e

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      script/pull_docker.sh

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      script/push_docker.sh

test: &test-and-store
  run:
    name: Run E2E Tests
    command: |
      cd /root/app/
      VIEWS='NYU NYUSH NYUAD NYSID BHS NYHS HSL'
      for VIEW in $VIEWS
      do
        git diff-tree --no-commit-id --name-only -r HEAD | grep /${VIEW}/
        if [[ $? == 0 ]]; then
          echo "Files changed in $VIEW package. Running tests."
          VIEW=$VIEW docker-compose run e2e cypress run --spec "cypress/integration/${VIEW}/**/*.spec.js" --reporter junit --reporter-options "mochaFile=test-results/${VIEW}/results-[hash].xml"
          docker cp "$(docker ps -q -a -l -f name=e2e)":/app/cypress cypress-results
          docker cp "$(docker ps -q -a -l -f name=e2e)":/app/test-results test-results
        else
          echo "No files changed in $VIEW package. Skipping tests."
        fi
      done

version: 2
jobs:
  build-and-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check package_jsons.tgz
          command: |
            script/tgz_packages.sh
            # CURRENT=$(sha256sum package_jsons.tgz | awk '{ print $1 }')
            # script/tgz_packages.sh
            # NEW=$(sha256sum package_jsons.tgz | awk '{ print $1 }')
            # if [[ $CURRENT == $NEW ]]; then
            #   echo 'success'
            # else
            #   echo 'A package.json file has changed. Run script/tgz_packages in your next commit to ensure your image has the latest node_modules.'
            # fi
      - <<: *auth_quay
      # - <<: *pull_docker
      - <<: *build_docker
      - <<: *test-and-store
      # - <<: *push_docker
      - store_artifacts:
          path: cypress-results/videos
      - store_artifacts:
          path: cypress-results/screenshots
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
  create-package:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      # - <<: *pull_docker
      - run:
          name: Build asset package and store
          command: |
            cd /root/app/
            VIEWS='NYU NYUSH NYUAD NYSID BHS NYHS HSL'
            for VIEW in $VIEWS
            do
              git diff-tree --no-commit-id --name-only -r HEAD | grep /${VIEW}/
              if [[ $? == 0 ]]; then
                export NODE_ENV=$([[ $CIRCLE_BRANCH = master ]] && echo "production" || echo "staging")
                VIEW=$VIEW docker-compose run create-package
                docker cp "$(docker ps -q -a -l -f name=create-package)":/app/packages packages
              else
                echo "No files changed in $VIEW package. Skipping build."
              fi
            done

      - store_artifacts:
          path: packages

workflows:
  version: 2
  build:
    jobs:
    - build-and-test
    - create-package:
        requires:
          - build-and-test

